### ISSUE TITLE
Scirius and ELK DBs

### ISSUE THREAD

**Issue by ManuelFFF** [StamusNetworks/SELKS#231]
Hi,

Would it be possible to get the locations of the Scirius and ELK databases within SELKS? 
I am considering a new way to backup my SELKS installation. The folder path where those DBs are located, that's all I need.
The idea is to keep only those folder synced for a fast and easy disaster recovery. If something happens, I would try to replace only the DBs with a recent copy, rather than the entire machine filesystem. 

Thank you

**Comment by pevma** [comment]
SELKS uses ES as the main DB for the data and storage.
Otherwise the other most important part is in the configs (suricata/moloch/local_settings.py)
This below would be to how automatically set up the rulesets in scirius for SELKS 6
https://github.com/StamusNetworks/SELKS/blob/SELKS6-ELK7-wip/staging/config/hooks/live/chroot-inside-Debian-Live.hook.chroot#L218

**Comment by ManuelFFF** [comment]
I will use that to build my backup solution.

Thank you!
