### ISSUE TITLE
ES Issues with migration - Fixed

### ISSUE THREAD

**Issue by brandonmreeves** [StamusNetworks/SELKS#75]
I have identified the issue with ES during the migration script that may still cause unassigned shards (even with the new upgrade script).

During the upgrade, the default ES template needs to be deleted before being added by running

curl -XDELETE http://localhost:9200/_template/*

This should go above line 256 in the upgrade script. 

If the default template does not take effect you can fix it by running the the attached script which is basically line 256 within a bash script (attached)
[fix_es.txt](https://github.com/StamusNetworks/SELKS/files/1007725/fix_es.txt)

**Comment by brandonmreeves** [comment]
If you do get unassigned shards, run the following command. It will tell you the reason why

curl -XGET localhost:9200/_cat/shards?h=index,shard,prirep,state,unassigned.reas

If the reason is "Unknown Index" it is because ES does not know what template to use for the created indexes and you should use the above fix. For future reference.

**Comment by pevma** [comment]
Good catch for SELKS4 testing!
I have just discovered the fix for that (i think) and it has to do that there are 2 outputs in the logstash.conf - so one takes the default template and thta may result in the unassigned shards. I had samoe help and discussion from the logstash IRC and it seems adding a template  to both the outputs will do the trick. 
https://github.com/StamusNetworks/SELKS/commit/d2f8d2c74c20b9b19878a4a0d995f8ff3cff44b1 
feedback is welcome!

**Comment by brandonmreeves** [comment]
That resolves it as well. Perfect No more Unassigned shards

**Comment by pevma** [comment]
Thank you for th e feedback.
